In [32]:
import numpy as np
a = np.array([[1,2,3],[2,5,6],[6,7,8]])

In [36]:
type(a[1][2])

numpy.int32

In [29]:
a.shape

(1, 3, 3)

In [35]:
a[1][0]

2

In [20]:
type(a[0])

numpy.ndarray

In [23]:
a

array([[1, 2, 3],
       [2, 5, 6]])

In [47]:
a = np.zeros((4,5))
b = np.random.randn(4,5)
print(b)
np.round(b,2,a)

[[ 0.77758742 -1.51092493 -1.02912717  0.15503532 -0.75181707]
 [ 1.59434654 -0.77872701 -0.43314806 -1.10231183  1.56365012]
 [ 0.28057971  0.37595288 -1.06634468 -0.74311538  0.64964376]
 [ 1.65735464  1.28005639 -2.85793178  0.40303318  0.57758462]]


array([[ 0.78, -1.51, -1.03,  0.16, -0.75],
       [ 1.59, -0.78, -0.43, -1.1 ,  1.56],
       [ 0.28,  0.38, -1.07, -0.74,  0.65],
       [ 1.66,  1.28, -2.86,  0.4 ,  0.58]])

In [48]:
a

array([[ 0.78, -1.51, -1.03,  0.16, -0.75],
       [ 1.59, -0.78, -0.43, -1.1 ,  1.56],
       [ 0.28,  0.38, -1.07, -0.74,  0.65],
       [ 1.66,  1.28, -2.86,  0.4 ,  0.58]])

In [49]:
b

array([[ 0.77758742, -1.51092493, -1.02912717,  0.15503532, -0.75181707],
       [ 1.59434654, -0.77872701, -0.43314806, -1.10231183,  1.56365012],
       [ 0.28057971,  0.37595288, -1.06634468, -0.74311538,  0.64964376],
       [ 1.65735464,  1.28005639, -2.85793178,  0.40303318,  0.57758462]])

In [40]:
np.random.randint(10,100,(6,5))

array([[57, 11, 99, 15, 95],
       [44, 59, 35, 22, 17],
       [67, 62, 57, 29, 93],
       [52, 67, 13, 15, 26],
       [32, 17, 18, 78, 43],
       [44, 54, 71, 62, 50]])

In [50]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [52]:
np.arange(4,20,4)

array([ 4,  8, 12, 16])

In [53]:
np.linspace(4,20,4)

array([ 4.        ,  9.33333333, 14.66666667, 20.        ])

In [55]:
a.ndim

2

In [58]:
a.shape[1]

5

In [62]:
a

array([[ 0.78, -1.51, -1.03,  0.16, -0.75],
       [ 1.59, -0.78, -0.43, -1.1 ,  1.56],
       [ 0.28,  0.38, -1.07, -0.74,  0.65],
       [ 1.66,  1.28, -2.86,  0.4 ,  0.58]])

In [66]:
np.reshape(a,(5,4))

array([[ 0.78, -1.51, -1.03,  0.16],
       [-0.75,  1.59, -0.78, -0.43],
       [-1.1 ,  1.56,  0.28,  0.38],
       [-1.07, -0.74,  0.65,  1.66],
       [ 1.28, -2.86,  0.4 ,  0.58]])

In [68]:
a[2][3] = 100

In [69]:
a

array([[  0.78,  -1.51,  -1.03,   0.16,  -0.75],
       [  1.59,  -0.78,  -0.43,  -1.1 ,   1.56],
       [  0.28,   0.38,  -1.07, 100.  ,   0.65],
       [  1.66,   1.28,  -2.86,   0.4 ,   0.58]])

In [70]:
a.transpose()

array([[  0.78,   1.59,   0.28,   1.66],
       [ -1.51,  -0.78,   0.38,   1.28],
       [ -1.03,  -0.43,  -1.07,  -2.86],
       [  0.16,  -1.1 , 100.  ,   0.4 ],
       [ -0.75,   1.56,   0.65,   0.58]])

In [76]:
a[:3, :3]

array([[ 0.78, -1.51, -1.03],
       [ 1.59, -0.78, -0.43],
       [ 0.28,  0.38, -1.07]])

In [82]:
a = np.random.randn(2,3)
b = np.random.randn(2,4)
np.hstack((a,b))

array([[-0.63114292, -0.50470837, -1.0183248 , -0.75284564,  1.723689  ,
         0.57128207, -1.42949577],
       [-0.24963924,  0.72106576,  0.37913025,  0.82098909,  0.64654651,
        -1.41383084, -0.31394096]])

In [ ]:
np.concatenate

In [91]:
import pandas as pd
import numpy

In [93]:
a = numpy.arange(10,20,2)
b = np.array([[5],[3]])
a+b

array([[15, 17, 19, 21, 23],
       [13, 15, 17, 19, 21]])

In [85]:
a

array([10, 12, 14, 16, 18])

In [88]:
b.shape

(2, 1)

In [90]:
b

array([[2],
       [3]])

In [94]:
l1 = [10,20,30]
l1[0]

10

In [99]:
l2 =[123,125,126]
label = ['day1', 'dau2', 'day3']
s1 = pd.Series(l2, label)
s1

day1    123
dau2    125
day3    126
dtype: int64

In [96]:
s1['dau2']

125

In [97]:
s1[1]

125

In [102]:

data = np.round(np.random.randn(3,5),4)
df = pd.DataFrame(data, ['x1', 'x2', 'x3'], ['A', 'B', 'C', 'D', 'E'])

In [103]:
df

A       B       C       D       E
x1 -1.8266  1.8275 -0.7990  0.3260  1.8521
x2  0.5583  0.1939  0.6801  0.0641  0.4169
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [119]:
df[['A','C']].iloc[0]

A   -1.8266
C   -0.7990
Name: x1, dtype: float64

In [108]:
a1 = df['A']
type(a1)

pandas.core.series.Series

In [109]:
a1 = df[['A']]
type(a1)

pandas.core.frame.DataFrame

In [111]:
df['new'] = df['A'] *df['B']
df

A       B       C       D       E       new
x1 -1.8266  1.8275 -0.7990  0.3260  1.8521 -3.338111
x2  0.5583  0.1939  0.6801  0.0641  0.4169  0.108254
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733 -0.106145

In [122]:
df.drop('new', axis =1, inplace=True)

KeyError: "['new'] not found in axis"

In [123]:
list1 = ['A', 'B', 'C']
df[list1]

A       B       C
x1 -1.8266  1.8275 -0.7990
x2  0.5583  0.1939  0.6801
x3 -0.3121  0.3401  0.6877

In [132]:
df.iloc[:, 0:3]

A       B       C
x1 -1.8266  1.8275 -0.7990
x2  0.5583  0.1939  0.6801
x3 -0.3121  0.3401  0.6877

In [134]:
df.loc['x2':'x3','A':'C']

A       B       C
x2  0.5583  0.1939  0.6801
x3 -0.3121  0.3401  0.6877

In [135]:
df

A       B       C       D       E
x1 -1.8266  1.8275 -0.7990  0.3260  1.8521
x2  0.5583  0.1939  0.6801  0.0641  0.4169
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [144]:
df[(df['C']>0.2) & (df['E']>0.5)]

A       B       C       D       E
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [139]:
df['D']>0.2

x1     True
x2    False
x3    False
Name: D, dtype: bool

In [146]:
df = pd.DataFrame(data,columns = ['A', 'B', 'C', 'D', 'E'])
df

A       B       C       D       E
0 -1.8266  1.8275 -0.7990  0.3260  1.8521
1  0.5583  0.1939  0.6801  0.0641  0.4169
2 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [150]:
df[(df['C']>0.2)].reset_index(drop=True)

A       B       C       D       E
0  0.5583  0.1939  0.6801  0.0641  0.4169
1 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [156]:
df.columns = list(np.arange(1,6))
df

1       2       3       4       5
0 -1.8266  1.8275 -0.7990  0.3260  1.8521
1  0.5583  0.1939  0.6801  0.0641  0.4169
2 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [159]:
b = list(np.arange(1,6))

In [160]:
a =['Name']*5

In [163]:
np.concatenate((a,b))

array(['Name', 'Name', 'Name', 'Name', 'Name', '1', '2', '3', '4', '5'],
      dtype='<U11')

In [164]:
df = pd.DataFrame(np.array([[1, 5, 1],[2, np.nan, 2],[np.nan, np.nan, 3]]))

df.columns = ['A', 'B', 'C']

df

A    B    C
0  1.0  5.0  1.0
1  2.0  NaN  2.0
2  NaN  NaN  3.0

In [165]:
df.fillna(0)

A    B    C
0  1.0  5.0  1.0
1  2.0  0.0  2.0
2  0.0  0.0  3.0

In [166]:
df.mean()

A    1.5
B    5.0
C    2.0
dtype: float64

In [167]:
df.fillna(df.mean())

A    B    C
0  1.0  5.0  1.0
1  2.0  5.0  2.0
2  1.5  5.0  3.0